### ISSUE TITLE
How to get action type name?

### ISSUE THREAD

**Issue by xiety** [granteagon/reduxr#1]
I'm using redux-saga and it requires me to pass an action name to it's takeLatest function. How can I get it from reduxr object? Someting like todoArray.type.create

**Comment by granteagon** [comment]
The action name should just be "create".  If you want to namespace it, you can pass a namespace on initialization of the reducer.

![image](https://user-images.githubusercontent.com/133823/30608724-41427246-9d47-11e7-9900-7e1ffcde3d70.png)

**Comment by xiety** [comment]
Manually create string constant from namespace and action name is the only way? I don't want to depend on implementation of full name generation. I want to take name from reduxr.

**Comment by granteagon** [comment]
Okay, I agree with you.  If you have an idea for implementation let me know.  I'll add a method to access action names today.

**Comment by granteagon** [comment]
After looking into this, I believe the action name is available to you already like this:
```js
console.log(todoArray.action.create().type);
// -> 'todoArray_create'
```
Let me know if that is a solution that works for you!

**Comment by xiety** [comment]
It works, thank you.

**Comment by granteagon** [comment]
Awesome!  Glad you are using the project!
